Nop.Plugin.Widgets.HomePageNewProductsPlugin/Controllers/WidgetsHomePageNewProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Plugin.Widgets.HomePageNewProductsPlugin.Models;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Widgets.HomePageNewProductsPlugin.Controllers
{

    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AdminAntiForgery]
    public class WidgetsHomePageNewProductsController : BasePluginController
    {
        private const string CONFIGURE_VIEW_PATH = "~/Plugins/Widgets.HomePageNewProductsPlugin/Views/WidgetsHomePageNewProducts/Configure.cshtml";
        private const string RESOURCE_KEY = "Admin.Plugins.Saved";

        private readonly IPermissionService _permissionService;
        readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly INotificationService _notificationService;
        private readonly ILocalizationService _localizationService;

        public WidgetsHomePageNewProductsController(IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext,
            INotificationService notificationService,
            ILocalizationService localizationService,
            IProductService productService)
        {
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
            _notificationService = notificationService;
            _localizationService = localizationService;
        }

        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
            {
                return AccessDeniedView();
            }

            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var homePageNewProductsSettings = _settingService.LoadSetting<HomePageNewProductsSettings>(storeScope);
            var model = new ConfigurationModel
            {
                WidgetZone = homePageNewProductsSettings.WidgetZone,
                NumberOfAddedProducts = homePageNewProductsSettings.NumberOfAddedProducts,
                ActiveStoreScopeConfiguration = storeScope,
            };

            if (storeScope > 0)
            {
                model.WidgetZone_OverrideForStore = _settingService.SettingExists(homePageNewProductsSettings, x => x.WidgetZone, storeScope);
                model.NumberOfAddedProducts_OverrideForStore = _settingService.SettingExists(homePageNewProductsSettings, x => x.NumberOfAddedProducts, storeScope);
            }

            return View(CONFIGURE_VIEW_PATH, model);
        }

        [HttpPost]
        public IActionResult Configure(ConfigurationModel model)
        {
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var homePageNewProductsSettings = _settingService.LoadSetting<HomePageNewProductsSettings>(storeScope);
            homePageNewProductsSettings.WidgetZone = model.WidgetZone;
            homePageNewProductsSettings.NumberOfAddedProducts = model.NumberOfAddedProducts;

            if (storeScope == 0)
            {
                _settingService.SaveSetting(homePageNewProductsSettings, x => x.NumberOfAddedProducts, storeScope, false);
                _settingService.SaveSetting(homePageNewProductsSettings, x => x.WidgetZone, storeScope, false);
            }
            else if (storeScope > 0)
            {
                _settingService.DeleteSetting(homePageNewProductsSettings, x => x.NumberOfAddedProducts, storeScope);
                _settingService.DeleteSetting(homePageNewProductsSettings, x => x.WidgetZone, storeScope);
            }

            _settingService.ClearCache();
            _notificationService.SuccessNotification(_localizationService.GetResource(RESOURCE_KEY));

            return Configure();
        }
    }
}

Nop.Plugin.Widgets.HomePageNewProductsPlugin/Views/WidgetsHomePageNewProducts/Configure.cshtml
@model Nop.Plugin.Widgets.HomePageNewProductsPlugin.Models.ConfigurationModel
@using Nop.Web.Framework

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

    <form asp-controller="WidgetsHomePageNewProducts" asp-action="Configure" method="post">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Configure
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label asp-for="WidgetZone" class="col-md-2 control-label">Select Widget Zone</label>
                        <div class="col-md-10">
                            <select asp-for="WidgetZone" asp-items="Html.GetEnumSelectList<Nop.Plugin.Widgets.HomePageNewProductsPlugin.WidgetZone>()">
                                <option value="">Select Zone</option>
                            </select>
                            <span asp-validation-for="WidgetZone" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="NumberOfAddedProducts" class="col-md-2 control-label">Number Of Added Products</label>
                        <div class="col-md-10">
                            <nop-editor asp-for="NumberOfAddedProducts" />
                            <span asp-validation-for="NumberOfAddedProducts"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <input type="submit" name="save" class="btn bg-blue" value="@T(" Admin.Common.Save")" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

Nop.Plugin.Widgets.HomePageNewProductsPlugin/Views/WidgetsHomePageNewProducts/PublicInfo.cshtml
@model IEnumerable<PublicViewModel>
@{
    Layout = "";
}

<div class="product-grid home-page-product-grid">
    <div class="title">
        <strong>@T(Constans.LATES_PRODUCTS_LOCAL_KEY)</strong>
    </div>

    <div class="item-grid">       
        @foreach (var product in Model)
        {
            var imageAltText = string.Format(T("Media.Product.ImageAlternateTextFormat").Text, product.Name);
            var imageTitleText = string.Format(T("Media.Product.ImageLinkTitleFormat").Text, product.Name);

            <div class="item-box">
                <div class="product-item" data-productid=@product.ProductId>
                    <div class="picture">
                        <a href=@Url.RouteUrl("Product", new { Name = product.Name })>
                            <img alt="@(imageAltText)" src="@product.PictureUrl" title="@(imageTitleText)">
                        </a>
                    </div>
                    <div class="details">
                        <h2 class="product-title">
                            <a href=@Url.RouteUrl("Product", new { Name = product.Name })>@product.Name</a>
                        </h2>
                        <div class="add-info">
                            <div class="prices">
                                <span class="price actual-price">@product.Price</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>